import type { Metadata } from "next"
import { Sora, Source_Sans_3 } from "next/font/google"
import "./globals.css"

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
})

const sourceSans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "João Victor - Developer",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${sourceSans3.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
